/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.laberinto.view;

import com.mycompany.laberinto.controller.ControladorPrincipal;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Paula
 */
public class PanelLaberinto extends javax.swing.JPanel {

    /**
     * Creates new form PanelLaberinto
     */
    private ControladorPrincipal controlador;
    private ImageIcon laberintoGrafico;

    private GUIPrincipal guiPrincipal;

    public PanelLaberinto(ControladorPrincipal controlador, GUIPrincipal guiPrincipal) {
        initComponents();
        this.controlador = controlador;
        this.guiPrincipal = guiPrincipal;
        laberintoGrafico = new ImageIcon("./src/main/resources/images/laberinto01.png");
    }

//    public void escuchar(ControladorLaberinto controlador){
//    this.controlador = controlador; 
//    }
    
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        laberintoGrafico.paintIcon(null, g, 0, 0);
        if (controlador != null) {
            controlador.dibujar(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
